spring:
  application:
    name: service1
  cloud:
    config:
      fail-fast: true
      uri: https://${config-server.address}:${config-server.port}
      username: luantv
      password: Luan5829$
#      profile: dev

#server:
#  port: 8081

my:
  custom:
    property: "Service 1 DEV Custom Property"