spring:
  application:
    name: service2
  cloud:
    config:
      fail-fast: true
      uri: https://${config-server.address}:${config-server.port}
      username: luantv
      password: Luan5829$
#      profile: uat

#server:
#  port: 8182

my:
  custom:
    property: "Service 2 UAT Custom Property"